### ISSUE TITLE
TODO (?) : make the combat more interactive and skill based by turning it into a reaction game

### ISSUE THREAD

**Issue by temp127389127389** [aber007/Dnd#41]
press too early: miss attack
press within 225ms: perfect attack, dmg multiplier 1.5
press within 450ms: normal attack
press after 450ms: miss attack

probably also add a chance for the enemy to miss their attack as well

in order for the combats to not be too long and thus too repetitive some balancing would be needed

**Comment by aber007** [comment]
Reaction Done. Enemy can still not miss attacks

**Comment by temp127389127389** [comment]
made reaction game out of dodging the attacks
